language: python
python:
#  - "2.7"
#  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
#  - "pypy"
  - "pypy3"
install:
  - python setup.py install
script: make test
after_script:
  - make coverage
  - pip install codeclimate-test-reporter
  - codeclimate-test-reporter
